accessModes:
    - ReadWriteOnce
resources:
   requests:
    storage: 1Gi
    cpu: 250m
    memory: 750Mi
container:
  name: grafana
image: grafana/grafana-enterprise
imagePullPolicy: IfNotPresent
ports:
    containerPort: 3000
    name: http-grafana
    protocol: TCP
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /robots.txt
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 2
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 3000
  timeoutSeconds: 1
volumeMounts:
    mountPath: /var/lib/grafana
    name: grafana-pv
volumes:
    name: grafana-pv
    persistentVolumeClaim:
      claimName: grafana-pvc
