apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ "grafana-pvc.fullname" }}
spec:
  accessModes:
    - {{toYaml .Values.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.resources.requests.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  lebels:
    app: {{.Values.container.name }}
  name: {{.Values.container.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.container.name}}
  template:
    metadata:
      app: {{ .Values.container.name}}
    spec:
      containers:
        - name: {{ .Values.container.name }} 
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{.Values.ports.containerPort }}
              name: {{.Values.ports.name}}
              protocol: {{.Values.ports.protocol}}
          readinessProbe:
            failureThreshold: {{.Values.readinessProbe.failureThreshold}}
            httpGet:
              path: {{.Values.readinessProbe.httpGet.path}}
              port: {{.Values.readinessProbe.httpGet.port}}
              scheme: {{.Values.readinessProbe.httpGet.scheme}}
            initialDelaySeconds: {{.Values.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.readinessProbe.periodSeconds}}
            successThreshold: {{.Values.readinessProbe.successThreshold}}
            timeoutSeconds: {{.Values.readinessProbe.timeoutSeconds}}
          livenessProbe: 
            failureThreshold: {{.Values.livenessProbe.failureThreshold}}
            initialDelaySeconds: {{.Values.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.livenessProbe.periodSeconds}}
            successThreshold: {{.Values.livenessProbe.successThreshold}}
            tcpSocket:
              port: {{.Values.livenessProbe.tcpSocket.port}}
            timeoutSeconds: {{.Values.livenessProbe.timeoutSeconds}}
          resources:
            requests:
              cpu: {{.Values.resources.requests.cpu}}
              memory: {{.Values.resources.requests.memory}}
          volumeMounts:
            - mountPath: {{.Values.volumeMounts.mountPath}} 
              name:  {{.Values.volumeMounts.name}} 
      volumes:
        - name: {{.Values.volumes.name}}
          persistentVolumeClaim:
            claimName: {{.Values.volumes.persistentVolumeClaim.claimName}}


