apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "grafana-pvc.fullname" . }}
spec:
  accessModes:
    {{- toYaml .Values.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.resources.requests.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  lebels:
    app: {{.Values.name}}
  name: {{.values.name}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      app: {{ .Values.name}}
    spec:
      securityContext:
        fsGroup: {{ .Values.spec.securityContext.fsGroup}}
        supplementalGroups:
        {{- .Values.Spec.securityContext.supplementalGroups | nindent 2}}
      containers:
        - name: {{ .Values.name.}} 
          image: {{ .Values.image. }}
          imagePullPolicy: {{ .Valies.imagePullPolicy }}
          ports:
            - containerPort: {{.Values.ports.containerPort }}
              name: {{.Values.containerPort.name}}
              protocol: {{.Values.containerPort.name.protocol}}
          readinessProbe:
            failureThreshold: {{.Values.readinessProbe.failureThreshold}}
            httpGet:
              path: {{.Values.readinessProbe.httpGet.path}}
              port: {{.Values.readinessProbe.httpGet.port}}
              scheme: {{.Values.readinessProbe.httpGet.scheme}}
            initialDelaySeconds: {{.Values.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.readinessProbe.periodSeconds}}
            successThreshold: {{.Values.readinessProbe.successThreshold}}
            timeoutSeconds: {{.Values.readinessProbe.timeoutSeconds}}
          livenessProbe: 
            failureThreshold: {{.Values.livenessProbe.failureThreshold}}
            initialDelaySeconds: {{.Values.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.livenessProbe.periodSeconds}}
            successThreshold: {{.Values.livenessProbe.successThreshold}}
            tcpSocket:
              port: {{.Values.livenessProbe.tcpSocket.port}}
            timeoutSeconds: {{.Values.livenessProbe.timeoutSeconds}}
          resources:
            requests:
              cpu: {{.values.resources.requests.cpu}}
              memory: {{.values.resources.requests.memory}}
          volumeMounts:
            - mountPath: {{.Values.volumeMounts.mountPath}} 
              name:  {{.Values.volumeMounts.name}} 
      volumes:
        - name: {{.Values.volumes.name}}
          persistentVolumeClaim:
            claimName: {{.Values.volumes.persistentVolumeClaim.claimName}}


